books = [
    {"abbr": "MAT", "chapters": 28}, {"abbr": "MRK", "chapters": 16}, {"abbr": "LUK", "chapters": 24},
    {"abbr": "JHN", "chapters": 21}, {"abbr": "ACT", "chapters": 28}, {"abbr": "ROM", "chapters": 16},
    {"abbr": "1CO", "chapters": 16}, {"abbr": "2CO", "chapters": 13}, {"abbr": "GAL", "chapters": 6},
    {"abbr": "EPH", "chapters": 6}, {"abbr": "PHP", "chapters": 4}, {"abbr": "COL", "chapters": 4},
    {"abbr": "1TH", "chapters": 5}, {"abbr": "2TH", "chapters": 3}, {"abbr": "1TI", "chapters": 6},
    {"abbr": "2TI", "chapters": 4}, {"abbr": "TIT", "chapters": 3}, {"abbr": "PHM", "chapters": 1},
    {"abbr": "HEB", "chapters": 13}, {"abbr": "JAS", "chapters": 5}, {"abbr": "1PE", "chapters": 5},
    {"abbr": "2PE", "chapters": 3}, {"abbr": "1JN", "chapters": 5}, {"abbr": "2JO", "chapters": 1},
    {"abbr": "3JO", "chapters": 1}, {"abbr": "JUD", "chapters": 1}, {"abbr": "REV", "chapters": 22},
    {"abbr": "GEN", "chapters": 50}, {"abbr": "EXO", "chapters": 40}, {"abbr": "LEV", "chapters": 27},
    {"abbr": "NUM", "chapters": 36}, {"abbr": "DEU", "chapters": 34}, {"abbr": "JOS", "chapters": 24},
    {"abbr": "JDG", "chapters": 21}, {"abbr": "RUT", "chapters": 4}, {"abbr": "1SA", "chapters": 31},
    {"abbr": "2SA", "chapters": 24}, {"abbr": "1KI", "chapters": 22}, {"abbr": "2KI", "chapters": 25},
    {"abbr": "1CH", "chapters": 29}, {"abbr": "2CH", "chapters": 36}, {"abbr": "EZR", "chapters": 10},
    {"abbr": "NEH", "chapters": 13}, {"abbr": "EST", "chapters": 10}, {"abbr": "JOB", "chapters": 42},
    {"abbr": "PSA", "chapters": 150}, {"abbr": "PRO", "chapters": 31}, {"abbr": "ECC", "chapters": 12},
    {"abbr": "SNG", "chapters": 8}, {"abbr": "ISA", "chapters": 66}, {"abbr": "JER", "chapters": 52},
    {"abbr": "LAM", "chapters": 5}, {"abbr": "EZK", "chapters": 48}, {"abbr": "DAN", "chapters": 12},
    {"abbr": "HOS", "chapters": 14}, {"abbr": "JOL", "chapters": 3}, {"abbr": "AMO", "chapters": 9},
    {"abbr": "OBA", "chapters": 1}, {"abbr": "JON", "chapters": 4}, {"abbr": "MIC", "chapters": 7},
    {"abbr": "NAM", "chapters": 3}, {"abbr": "HAB", "chapters": 3}, {"abbr": "ZEP", "chapters": 3},
    {"abbr": "HAG", "chapters": 2}, {"abbr": "ZEC", "chapters": 14}, {"abbr": "MAL", "chapters": 4} 
]
